# -*- coding: utf-8 -*-
"""Assignment 1- Software Modeling

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OfN35uO7_zu1tvvWJS9r8aFeUjKSY3_0
"""

#here i created a class that is boarding pass that
#has the atributes that demonstraigh details about the
#flight and destination and information about the passenger including there name
class BoardingPass:
    def __init__(self, passenger_name, flight_number, seat_number, departure_airport, destination_airport, departure_date, departure_time):
        self._passenger_name = passenger_name
        self._flight_number = flight_number
        self._seat_number = seat_number
        self._departure_airport = departure_airport
        self._destination_airport = destination_airport
        self._departure_date = departure_date
        self._departure_time = departure_time
        self._is_checked_in = False
        self._is_boarded = False
#here i used  self to be able to acess the attributes and access them through methods such as get and set
    # Getter methods, the getter method is used in Oject Oriented Programing that help acess private atributes.
    def get_passenger_name(self):
        return self._passenger_name

    def get_flight_number(self):
        return self._flight_number

    def get_seat_number(self):
        return self._seat_number

    def get_departure_airport(self):
        return self._departure_airport

    def get_destination_airport(self):
        return self._destination_airport

    def get_departure_date(self):
        return self._departure_date

    def get_departure_time(self):
        return self._departure_time

    def is_checked_in(self):
        return self._is_checked_in

    def is_boarded(self):
        return self._is_boarded

    # Setter methods, the setter method is used in object oriented programming that help acess private attributes.
    def set_passenger_name(self, new_name):
        self._passenger_name = new_name

    def set_flight_number(self, new_flight_number):
        self._flight_number = new_flight_number

    def set_seat_number(self, new_seat_number):
        self._seat_number = new_seat_number

    def set_departure_airport(self, new_departure_airport):
        self._departure_airport = new_departure_airport

    def set_destination_airport(self, new_destination_airport):
        self._destination_airport = new_destination_airport

    def set_departure_date(self, new_departure_date):
        self._departure_date = new_departure_date

    def set_departure_time(self, new_departure_time):
        self._departure_time = new_departure_time

    def check_in(self):
        self._is_checked_in = True
        print(f"Check-in successful for {self._passenger_name} on Flight {self._flight_number}.")

    def board_flight(self):
        self._is_boarded = True
        print(f"Passenger {self._passenger_name} has boarded Flight {self._flight_number}.")

# Here i created an example of Boarding pass this means that this example is an object of BoardingPass because it is an instance.
my_ticket = BoardingPass(
    passenger_name="Hessa Mohammad",
    flight_number="ABC123",
    seat_number="12A",
    departure_airport="ZRH	Zürich Airport",
    destination_airport="FLR  Florance",
    departure_date="2024-02-24",
    departure_time="14:30"
)

# Accessing attributes using getters
print(f"Passenger: {my_ticket.get_passenger_name()}")
print(f"Flight: {my_ticket.get_flight_number()}, Seat: {my_ticket.get_seat_number()}")
print(f"Departure: {my_ticket.get_departure_airport()}, Destination: {my_ticket.get_destination_airport()}")
print(f"Departure Date: {my_ticket.get_departure_date()}, Departure Time: {my_ticket.get_departure_time()}")

# Calling methods
my_ticket.check_in()
my_ticket.board_flight()

#Here i created another class that talks and shows the speficationof the an airplane that include engine type, mileage, seat count etc..
class Airplane:
    def __init__(self, airline, mileage, seat_count, engine, airplane_id):
        self._airline = airline
        self._mileage = mileage
        self._seat_count = seat_count
        self._engine = engine
        self._airplane_id = airplane_id


#here i used  self to be able to acess the attributes and access them through methods such as get and set
    # Getter methods, the getter method is used in Oject Oriented Programing that help acess private atributes.

    def get_airline(self):
        return self._airline

    def get_mileage(self):
        return self._mileage

    def get_seat_count(self):
        return self._seat_count

    def get_engine(self):
        return self._engine

    def get_airplane_id(self):
        return self._airplane_id

    # Setter methods, the setter method is used in object oriented programming thathekp acess private attributes.
    def set_airline(self, airline):
        self._airline = airline

    def set_hours(self, mileage):
        self._mileage = mileage

    def set_seat_count(self, seat_count):
        self._seat_count = seat_count

    def set_engine(self, engine):
        self._engine = engine

    def set_airplane_id(self, airplane_id):
        self._airplane_id = airplane_id

#Here i created an example of Airplane to show the different attrubites and how they take up different values
#this makes my-airplane an object of Airplane since it is an example or an instance
my_airplane = Airplane(
    airline="Delta Airline",
    mileage=500000,
    seat_count=420,
    engine="Twin Jet",
    airplane_id="EA123"
)

# Example of using getter methods
print(f"Airplane ID: {my_airplane.get_airplane_id()}")
print(f"Airline: {my_airplane.get_airline()}")
print(f"Flight Mileage: {my_airplane.get_mileage()}")
print(f"Seat Count: {my_airplane.get_seat_count()}")
print(f"Engine: {my_airplane.get_engine()}")

# Example of using setter methods to update the airplane's airline
my_airplane.set_airline("Emirates Airline")
print(f"Updated Airline: {my_airplane.get_airline()}")

#here i created a class that is called flight that gives flight details that allow the passenger tp stay update on whether the flight is delayed, cancled or on time.
class Flight:
    def __init__(self, crew_number, terminal, number_of_passengers, airplane, duration, delayed=False, canceled=False):
        self._crew_number = crew_number
        self._terminal = terminal
        self._number_of_passengers = number_of_passengers
        self._airplane = airplane
        self._duration= duration
        self._delayed = delayed
        self._canceled = canceled
#here i used  self to be able to acess the attributes and access them through methods such as get and set
    # Getter methods, the getter method is used in Oject Oriented Programing that help acess private atributes

    def get_crew_number(self):
        return self._crew_number

    def get_terminal(self):
        return self._terminal

    def get_number_of_passengers(self):
        return self._number_of_passengers

    def get_airplane(self):
        return self._airplane

    def get_duration(self):
        return self._duration


    def is_delayed(self):
        return self._delayed

    def is_canceled(self):
        return self._canceled

    # Setter methods, the setter method is used in object oriented programming thathekp acess private attributes.
    def set_crew_number(self, crew_number):
        self._crew_number = crew_number

    def set_terminal(self, terminal):
        self._terminal = terminal

    def set_number_of_passengers(self, number_of_passengers):
        self._number_of_passengers = number_of_passengers

    def set_airplane(self, airplane):
        self._airplane = airplane

    def set_duration(self,duration):
        self._duration = duration

    def set_delayed(self, delayed):
        self._delayed = delayed

    def set_canceled(self, canceled):
        self._canceled = canceled

    def update_flight_status(self, delayed=None, canceled=None):
          """Update the flight status based on delays or cancellations"""
          pass  # Placeholder for the beginning of the method, typically not necessary when actual code follows
          if delayed is not None:  # Check if the 'delayed' status has been provided
            self._delayed = delayed  # Update the internal '_delayed' flag based on the input
            status = "delayed" if delayed else "on time"  # Determine the new status message based on the 'delayed' flag
            print(f"Flight status has been updated to {status}.")  # Print the updated flight status

          if canceled is not None:  # Check if the 'canceled' status has been provided
            self._canceled = canceled  # Update the internal '_canceled' flag based on the input
            status = "canceled" if canceled else "scheduled"  # Determine the new status message based on the 'canceled' flag
            print(f"Flight has been {status}.")  # Print the updated flight cancellation status

    def board_passengers(self):
        """Manage the boarding process for passengers"""
        pass  # Placeholder for the beginning of the method, typically not necessary when actual code follows
        if self._canceled:  # Check if the flight has been canceled
          print("Flight has been canceled. Boarding will not proceed.")  # Inform that boarding will not proceed due to cancellation
        elif self._delayed:  # Else, check if the flight is delayed
          print("Flight is delayed. Please wait for further announcements.")  # Inform passengers of the delay and to wait for further info
        else:  # If the flight is neither canceled nor delayed
          print(f"Boarding has started for {self._number_of_passengers} passengers at Terminal {self._terminal}.")  # Begin the boarding process


# Example usage:
my_flight = Flight(
    crew_number=4,
    terminal="3B",
    number_of_passengers=350,
    airplane="Airbus A320",
    duration=12,
    delayed=False,  # Initially, the flight might not be delayed
    canceled=False  # Initially, the flight is not canceled
)

# Now, to update the flight status to indicate it is canceled
my_flight.update_flight_status(canceled=True)

# This will set the _canceled attribute to True and print a message indicating the flight has been canceled.


# Accessing attributes using getters
print(f"Crew Number: {my_flight.get_crew_number()}")
print(f"Terminal: {my_flight.get_terminal()}")
print(f"Number of Passengers: {my_flight.get_number_of_passengers()}")
print(f"Airplane: {my_flight.get_airplane()}")
print(f"Duration of flight in hours: {my_flight.get_duration()}")
print(f"Delayed: {my_flight.is_delayed()}")
print(f"Canceled: {my_flight.is_canceled()}")

# Updating attributes using setters
my_flight.set_delayed(False)
my_flight.set_canceled(False)
print(f"Updated Delayed Status: {my_flight.is_delayed()}")
print(f"Updated Canceled Status: {my_flight.is_canceled()}")

# Assuming you have an instance of the Flight class named my_flight
my_flight = Flight(
    crew_number=4,
    terminal="3B",
    number_of_passengers=200,
    airplane="Airbus A320",
    delayed=False,  # Initially, the flight might not be delayed
    canceled=False  # Initially, the flight is not canceled
)

# Now, to update the flight status to indicate it is canceled
my_flight.update_flight_status(canceled=True)

# This will set the _canceled attribute to True and print a message indicating the flight has been canceled.

#here i created a class called passenger where we are able to see personal deatils about the passenger and these deatils can be updated through the setter methods
class Passenger:
    def __init__(self, first_name, last_name, age, ID_number, phone_number, email_id, nationality):
        self._first_name = first_name
        self._last_name = last_name
        self._age = age
        self._ID_number = ID_number
        self._phone_number = phone_number
        self._email_id = email_id
        self._nationality = nationality

    # Getter methods
    def get_first_name(self):
        return self._first_name

    def get_last_name(self):
        return self._last_name

    def get_age(self):
        return self._age

    def get_ID_number(self):
        return self._ID_number

    def get_phone_number(self):
        return self._phone_number

    def get_email_id(self):
        return self._email_id

    def get_nationality(self):
        return self._nationality

    # Setter methods
    def set_first_name(self, first_name):
        self._first_name = first_name

    def set_last_name(self, last_name):
        self._last_name = last_name

    def set_age(self, age):
        self._age = age

    def set_ID_number(self, ID_number):
        self._ID_number = ID_number

    def set_phone_number(self, phone_number):
        self._phone_number = phone_number

    def set_email_id(self, email_id):
        self._email_id = email_id

    def set_nationality(self, nationality):
        self._nationality = nationality

    # Placeholder for additional functionality
    def update_passenger_info(self):
        """Placeholder method to update passenger's information"""
        pass

# Example of creating an instance of the Passenger class
my_passenger = Passenger(
    first_name="Saeed",
    last_name="Abdallah",
    age=30,
    ID_number="ID123456",
    phone_number="123-456-7890",
    email_id="Saeed.Abdualla@gamil.com",
    nationality="Emirati"
)

# Example of using getter methods
print(f"Passenger: {my_passenger.get_first_name()} {my_passenger.get_last_name()}")
print(f"Age: {my_passenger.get_age()}, ID Number: {my_passenger.get_ID_number()}")
print(f"Phone: {my_passenger.get_phone_number()}, Email: {my_passenger.get_email_id()}")
print(f"Nationality: {my_passenger.get_nationality()}")

# Example of using setter methods to update the passenger's phone number
my_passenger.set_phone_number("987-654-3210")
print(f"Updated Phone: {my_passenger.get_phone_number()}")

#here i created a class that takes details about the staff crew and their hour shifts, this later on determines if they are able to board the flight or not.
class StaffCrew:
    def __init__(self, first_name, last_name, age, employee_number, email_id, shift_hours):
        self._first_name = first_name
        self._last_name = last_name
        self._age = age
        self._employee_number = employee_number
        self._email_id = email_id
        self._shift_hours = shift_hours

    # Getter methods
    def get_first_name(self):
        return self._first_name

    def get_last_name(self):
        return self._last_name

    def get_age(self):
        return self._age

    def get_employee_number(self):
        return self._employee_number

    def get_email_id(self):
        return self._email_id

    def get_shift_hours(self):
        return self._shift_hours

    # Setter methods
    def set_first_name(self, first_name):
        self._first_name = first_name

    def set_last_name(self, last_name):
        self._last_name = last_name

    def set_age(self, age):
        self._age = age

    def set_employee_number(self, employee_number):
        self._employee_number = employee_number

    def set_email_id(self, email_id):
        self._email_id = email_id

    def set_shift_hours(self, shift_hours):
    # Check if the provided shift_hours exceed the maximum allowed limit
        if shift_hours > 20:
        # Print a warning message if shift hours exceed 20 hours
           print("Shift hours cannot exceed 10 hours for safety reasons.")
        else:
        # Assign the provided shift_hours to the staff member if within the allowed limit
            self._shift_hours = shift_hours

    def can_board_flight(self):
        """Check if the staff crew member is allowed to board the flight based on shift hours."""
    # Check if the staff member's shift hours exceed the maximum limit for boarding
        if self._shift_hours > 20:
        # Return False if shift hours are more than 20, indicating the staff cannot board the flight
          return False
        else:
        # Return True if shift hours are within the limit, allowing staff to board the flight
          return True

# Placeholder for additional functionality
    def schedule_shift(self):
        """Placeholder method to schedule or update the staff crew's shift"""
    # Placeholder functionality to be implemented later
        pass


# Example of creating an instance of the StaffCrew class with more than 10 shift hours
my_staff = StaffCrew(
    first_name="Alice",
    last_name="Johnson",
    age=28,
    employee_number="EMP12345",
    email_id="alice.johnson@example.com",
    shift_hours=25  # This will trigger a warning a
)

# Check if the staff member can board the flight
if my_staff.can_board_flight():
    print(f"{my_staff.get_first_name()} {my_staff.get_last_name()} is allowed to board the flight.")
else:
    print(f"{my_staff.get_first_name()} {my_staff.get_last_name()} is not allowed to board the flight due to long shift hours.")


print(f"Staff Member: {my_staff.get_first_name()} {my_staff.get_last_name()}")
print(f"Age: {my_staff.get_age()}, Employee Number: {my_staff.get_employee_number()}")
print(f"Email: {my_staff.get_email_id()}, Shift Hours: {my_staff.get_shift_hours()}")

# Example of using setter methods to update the staff member's email
my_staff.set_email_id("alice.j.new@example.com")
print(f"Updated Email: {my_staff.get_email_id()}")